// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LoginApp
{
	public partial class LoginViewController : UIViewController
	{
        public event EventHandler OnLoginSuccess;

        NSUserDefaults plist = NSUserDefaults.StandardUserDefaults;

		public LoginViewController (IntPtr handle) : base (handle)
		{
		}


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            btnEntrar.TouchUpInside += BtnEntrar_TouchUpInside;

        }

        void BtnEntrar_TouchUpInside(object sender, EventArgs e)
        {
            /*if (OnLoginSuccess != null)
            {
                OnLoginSuccess(sender, new EventArgs());
            }*/

            string usuario = txtUsuario.Text;
            string pass = txtPassword.Text;

            if (usuario.Equals("felipe") && pass.Equals("felipe"))
            {
                plist.SetString(usuario,"usuario");
               

                OnLoginSuccess?.Invoke(sender, new EventArgs());
            }


        }
    }
}
