// This file has been autogenerated from a class added in the UI designer.

using System;
using Entidades;
using Foundation;
using UIKit;

namespace AppSQLite
{
	public partial class EditarViewController : UIViewController
	{
        public Empresa objEmpresa { get; set; }

        Utilidades objUtilidades;

        Conexion objConexion;

		public EditarViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            objUtilidades = new Utilidades(this);

            objConexion = new Conexion();

            NavigationController.NavigationBar.PrefersLargeTitles = false;

            txtRfc.Text = objEmpresa.RFC;

            txtRfc.ShouldReturn += delegate (UITextField textField)
            {
                textField.ResignFirstResponder();
                return true;
            };

            btnGuardar.TouchUpInside += delegate {

                try
                {
                    //Inseraccion de la informacion

                    objEmpresa.RFC = txtRfc.Text;

                    int resultado = objConexion.conexion.Update(objEmpresa);

                    if (resultado == 1)
                    {
                        objUtilidades.MessageBox("Empresa", "Se modifico correctamente", "Alert");
                    }

                }
                catch (Exception ex)
                {
                    objUtilidades.MessageBox("Empresa", "Hubo un error " + ex.Message, "Alert");
                }
            };
        }
	}
}
